/// Flutter icons FlutterIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterIcon
///      fonts:
///       - asset: fonts/FlutterIcon.ttf
///
///
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class FlutterIcon {
  FlutterIcon._();

  static const _kFontFam = 'FlutterIcon';

  static const IconData phone = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData off = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData bug_report =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData group = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData setting = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData mail = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData th_large_outline =
      const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData megaphone =
      const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData thumbs_up =
      const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData paper_plane =
      const IconData(0xf01d, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xf0e6, fontFamily: _kFontFam);
}
